[[headers]]
    for = "/*"

    [[headers.values]]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

        cache-control = '''
	    public,
        max-age=15552000,'''